name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          micromamba-version: '1.4.2'
          environment-file: 'script/build-environment.yml'

      - name: Build the gallery site
        if: github.ref == 'refs/heads/main'
        shell: bash -l {0}
        run: |
          set -eux
          npm install
          npm run build

      - name: Build the gallery site in debug-mode
        if: github.ref != 'refs/heads/main'
        shell: bash -l {0}
        run: |
          set -eux
          npm install
          npm run build:dev

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
